### ISSUE TITLE
feature request: bound interface

### ISSUE THREAD

**Issue by ruokeqx** [prometheus-community/pro-bing#85]
is it possible to provide some method to bind interface like ping do?

```
ping [-AaCDdfnoQqRrv] [-b boundif] 
     -b boundif
             Bind the socket to interface boundif for sending.  This option is an Apple addition.
```

use control function in ListenConfig is one option, but may need change x/icmp to net.ListenConfig

**Comment by fjbotha** [comment]
You should be able to configure `Pinger.InterfaceName`. It works on Linux.

**Comment by ruokeqx** [comment]
close due to implemented in https://github.com/prometheus-community/pro-bing/pull/123
